### ISSUE TITLE
Does it only show real-time deals, or ones since the last check

### ISSUE THREAD

**Issue by Gitoffthelawn** [jonathanmccann/slickdeals-alert-firefox-addon#1]
Interesting idea for an extension!

Does it only show real-time deals as they are created, or does it also show ones since the last time the browser was opened?

**Comment by jonathanmccann** [comment]
Yes, this only shows new deals since the browser has been opened. I didn't want to have to save anything to the user's computer (not sure if that's even possible) and I also didn't want someone to be bombarded with alerts if they haven't opened the browser in some time.

**Comment by Gitoffthelawn** [comment]
Thanks for the clarification and logic behind it! :)
